### PR TITLE
Correct installation.md

### PR DESCRIPTION
**Pull request by clemensk1**
fixed "unknown TYK_MODE ce" error

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [ ] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [x] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor` in applicable directories.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `gofmt -s -w .`
  - [ ] `go vet ./...`
  - [ ] `golangci-lint run`

### CODE REVIEW

**Comment by asoorm** [comment]
Hi @clemensk1 please checkout to a specific tag: https://github.com/TykTechnologies/tyk-operator/tree/v0.5.0

We are unifying the operator configuration options to say `ce` rather than `oss`. And release 0.6.0 will support both modes. I think you got caught in a situation whereby `master` in git is not `latest` in the Operator on DockerHub.

Apologies for the complication / confusion.

cc @gernest @alephnull

**Comment by clemensk1** [comment]
Hi!

I checked out to v0.5.0, still the same error.
I also tried with the docker image v0.3.0 and v0.4.0. None of them seems to accept "ce" as valid TYK_MODE

**Comment by asoorm** [comment]
@clemensk1 - please set `TYK_MODE=oss`. And it will work. What I meant was that the documentation is correct if you checkout tag `0.5.0`.

**Comment by gernest** [comment]
@clemensk1 
Unfortunate the changes are still on master branch which doesn't have a docker image. These docs are for expected `v0.6.0` release.

**Comment by gernest** [comment]
`v0.6.0` have been released . The docker images now reflect the changes.
I'm closing this for now.

**Pull request closed without merging**
