### PR TITLE
Added new mock endpoint sample

### PR DESCRIPTION
**Pull request by rewsmith**
Added a new mock endpoint to the samples

## Description

Not much more to say!

## Motivation and Context

We don't currently have a mock sample.  The more samples the better.

## Test Coverage For This Change

k apply -f httpbin_mock.yaml -n tyk

curl localhost:8080/httpbin/foo
{"foo": "bar"}%

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [ ] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] Make sure you are updating [CHANGELOG.md](https://github.com/TykTechnologies/tyk-operator/blob/master/CHANGELOG.md) based on your changes.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] If you've changed API models, please update CRDs.
  - [ ] `make manifests`
  - [ ] `make helm`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `gofmt -s -w .`
  - [ ] `go vet ./...`
  - [ ] `golangci-lint run`

### CODE REVIEW

**Review by buraksekili — APPROVED** [review]
thank you @rewsmith !

**Comment by rewsmith** [comment]
@buraksekili Can this be merged now?

**Comment by buraksekili** [comment]
@rewsmith,  it requires testing from QA before merging; that's why I haven't merged it yet.

**Comment by rewsmith** [comment]
@buraksekili Ah ok, I'll leave it with you then :-)

**Comment by rewsmith** [comment]
@buraksekili @asoorm Just added sample to APIDefinition markdown doc page

**Pull request merged**
