### PR TITLE
TT-5674 - Add GraphQL introspection

### PR DESCRIPTION
**Pull request by buraksekili**
## Description
This PR adds GraphQL introspection to the ApiDefinition controller. So that, Operator introspects graphql servers for Subgraph and Supergraph APIs.

## Motivation and Context
It will help Tyk Operator to automate GraphQL Federation on the k8s environment.
## Test Coverage For This Change

e2e tests will be added subsequently.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [x] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [x] Make sure you are updating [CHANGELOG.md](https://github.com/TykTechnologies/tyk-operator/blob/master/CHANGELOG.md) based on your changes.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [x] I have updated the documentation accordingly.
- [x] If you've changed API models, please update CRDs.
  - [x] `make manifests`
  - [x] `make helm`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [x] `gofmt -s -w .`
  - [x] `go vet ./...`
  - [x] `golangci-lint run`

### CODE REVIEW

**Comment by buraksekili** [comment]
closed for now

**Comment by ilterpehlivan** [comment]
@buraksekili - May I ask why this PR is closed ? Currently it is quite complex to configure the federation and We could not manage it after couple of try and honestly that is why thinking to drop idea of using Tyk. Then I saw this PR and wondering how come !
Could you please explain ?
Thanks

**Comment by buraksekili** [comment]
hi @ilterpehlivan, the PR was closed mainly due to concerns mentioned here: https://github.com/TykTechnologies/tyk-operator/issues/587#issuecomment-1471513664.

If you have APIs using GraphQL Federation, you may want to check [snapshot tool](https://github.com/TykTechnologies/tyk-operator/tree/master/pkg/snapshot) that helps exporting APIs from Tyk Dashboard to Kubernetes CRD. As Tyk Dashboard allows introspection, your API can be exported in ApiDefinition CR format via snapshot tool. Or, some workflow is needed,  where introspection is triggered after creating an ApiDefinition CR.

**Comment by ilterpehlivan** [comment]
tesekkur @buraksekili :) for prompt answer. I understand the reason and definitely makes sense. However for the people who are using community version, this comes with limitations! I would be evaluating the options
Thanks again

**Pull request closed without merging**
